# [(10주차) 5월 6일](https://guebin.github.io/IP2022/2022/05/04/(10%EC%A3%BC%EC%B0%A8)-5%EC%9B%946%EC%9D%BC.html)

판다스를 왜 써야할까?, pandas 개발동기

## import

In [1]:
import numpy as np
import pandas as pd

## 부분 데이터 꺼내기: 판다스를 왜 써야할까?

### 기본 인덱싱

`-` 예제1: 기본인덱싱

In [2]:
a = 'asdf'
a[2]

'd'

In [3]:
a[-1]

'f'

`-` 예제2: 슬라이싱

In [4]:
a='asdf'
a[1:3]

'sd'

`-` 예제3: 스트라이딩

In [6]:
a='asdf'
a[::2] # 1번째, 3번째 원소 출력

'ad'

`-` 예제4: 불가능한 것

In [8]:
a = 'asdf'
a[[1,2]] # 정수인덱스를 리스트화 시켜서 인덱싱하는 것을 불가능

TypeError: string indices must be integers

### 팬시인덱싱

`-` 예제1: 인덱스의 리스트 (혹은 ndarray)를 전달

In [11]:
a = np.arange(5)
a,a[[1,2,-1]]

(array([0, 1, 2, 3, 4]), array([1, 2, 4]))

In [13]:
a = np.arange(55,61)
a, a[[1,2,-1]]

(array([55, 56, 57, 58, 59, 60]), array([56, 57, 60]))

`-` 예제2: bool로 이루어진 리스트 (혹은 ndarray)를 전달

In [15]:
a[[True, True, False, False, False, False]]

array([55, 56])

In [17]:
a[np.array([True, True, False, False, False, False])] # 꼭 리스트로 전달할 필요는 없음.

array([55, 56])

In [18]:
a[a<58]

array([55, 56, 57])

### 2차원자료형의 인덱싱

`-` 예제1

In [19]:
a = np.arange(4*3).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
a[0:2,1]

array([1, 4])

`-` 예제2: 차원을 유지하면서 인덱싱을 하고 싶으면?

In [22]:
a = np.arange(4*3).reshape(4,3)
a[0:2, [1]]

array([[1],
       [4]])

### Hash

`-` 예제1: (key, value)o

In [23]:
d = {'att':65, 'rep':45, 'mid':30, 'fin':100}
d

{'att': 65, 'rep': 45, 'mid': 30, 'fin': 100}

In [25]:
d['att'] # key를 넣으면 value가 리턴

65

`-` 예제2: numpy와 비교

In [26]:
np.random.seed(43052)
att = np.random.choice(np.arange(10,21)*5,200)
rep = np.random.choice(np.arange(5,21)*5,200)
mid = np.random.choice(np.arange(0,21)*5,200)
fin = np.random.choice(np.arange(0,21)*5,200)
key = ['202212'+str(s) for s in np.random.choice(np.arange(300,501),200,replace=False)]
test_dic = {key[i] : {'att':att[i], 'rep':rep[i], 'mid':mid[i], 'fin':fin[i]} for i in range(200)}
test_ndarray = np.array([key,att,rep,mid,fin],dtype=np.int64).T
del(att);del(rep);del(mid);del(fin);del(key)

In [28]:
#test_dic

학번 `202212460`에 해당하는 학생의 출석점수를 알고 싶다면?

`-` (풀이1)

In [29]:
test_dic['202212460']['att'] ## 가독성이 좋음.

55

`-` (풀이2)

In [35]:
test_ndarray[test_ndarray[:,0] == 202212460, 1] ## 가독성이 떨어짐.

array([55])

정보를 뽑을 때 Numpy indexing을 이용하는 것보다 딕셔너리를 이용하고 hash 타입으로 접근하는것이 편리할 때가 많이 있다.

**(풀이2)가 (풀이1)에 비하여 불편한 점**

- test_ndarray의 첫칼럼은 student id 이고 두번째 칼럼은 att라는 사실을 암기하고 있어야 한다.

- student id가 아니고 만약에 학생이름을 써서 데이터를 정리한다면 모든 자료형은 문자형이 되어야 한다.

- 작성한 코드의 가독성이 없다. (위치로 접근하기 때문)

`-` 요약: hash 스타일로 정보를 추출하는 것이 유용할 때가 있다. 그리고 보통 hash 스타일로 정보를 뽑는 것이 유리하다. (사실 Numpy는 정보추출을 위해 개발된 자료형이 아니라 행렬 및 벡터의 수학연산을 지원하기 위해 개발된 자료형이다.)

`-` 소망: 정보를 추출할때는 hash 스타일도 유용하다는 것은 이해함 $\to$ 하지만 나는 넘파이스타일로 정보를 뽑고 싶은걸? 그리고 딕셔너리 형태가 아니고 엑셀처럼(행렬처럼) 데이터를 보고 싶은걸? $\to$ pandas의 개발

## pandas 개발동기

### 엑셀처럼 데이터를 테이블 형태로 정리하고 싶다.

In [36]:
np.random.seed(43052)
att = np.random.choice(np.arange(10,21)*5,20)
rep = np.random.choice(np.arange(5,21)*5,20)
mid = np.random.choice(np.arange(0,21)*5,20)
fin = np.random.choice(np.arange(0,21)*5,20)
key = ['202212'+str(s) for s in np.random.choice(np.arange(300,501),20,replace=False)]
test_dic = {key[i] : {'att':att[i], 'rep':rep[i], 'mid':mid[i], 'fin':fin[i]} for i in range(20)}

In [37]:
test_dic

{'202212380': {'att': 65, 'rep': 55, 'mid': 50, 'fin': 40},
 '202212370': {'att': 95, 'rep': 100, 'mid': 50, 'fin': 80},
 '202212363': {'att': 65, 'rep': 90, 'mid': 60, 'fin': 30},
 '202212488': {'att': 55, 'rep': 80, 'mid': 75, 'fin': 80},
 '202212312': {'att': 80, 'rep': 30, 'mid': 30, 'fin': 100},
 '202212377': {'att': 75, 'rep': 40, 'mid': 100, 'fin': 15},
 '202212463': {'att': 65, 'rep': 45, 'mid': 45, 'fin': 90},
 '202212471': {'att': 60, 'rep': 60, 'mid': 25, 'fin': 0},
 '202212400': {'att': 95, 'rep': 65, 'mid': 20, 'fin': 10},
 '202212469': {'att': 90, 'rep': 80, 'mid': 80, 'fin': 20},
 '202212318': {'att': 55, 'rep': 75, 'mid': 35, 'fin': 25},
 '202212432': {'att': 95, 'rep': 95, 'mid': 45, 'fin': 0},
 '202212443': {'att': 95, 'rep': 55, 'mid': 15, 'fin': 35},
 '202212367': {'att': 50, 'rep': 80, 'mid': 40, 'fin': 30},
 '202212458': {'att': 50, 'rep': 55, 'mid': 15, 'fin': 85},
 '202212396': {'att': 95, 'rep': 30, 'mid': 30, 'fin': 95},
 '202212482': {'att': 50, 'rep': 50, 'm

- 테이블형태로 보고싶다.

(방법1) -- 행렬이기는 하지만 방법 2,3,4,5에 비하여 우리가 원하는 만큼 가독성을 주는 형태는 아님.

In [38]:
test_ndarray = np.array([key,att,rep,mid,fin],dtype=np.int64).T
test_ndarray

array([[202212380,        65,        55,        50,        40],
       [202212370,        95,       100,        50,        80],
       [202212363,        65,        90,        60,        30],
       [202212488,        55,        80,        75,        80],
       [202212312,        80,        30,        30,       100],
       [202212377,        75,        40,       100,        15],
       [202212463,        65,        45,        45,        90],
       [202212471,        60,        60,        25,         0],
       [202212400,        95,        65,        20,        10],
       [202212469,        90,        80,        80,        20],
       [202212318,        55,        75,        35,        25],
       [202212432,        95,        95,        45,         0],
       [202212443,        95,        55,        15,        35],
       [202212367,        50,        80,        40,        30],
       [202212458,        50,        55,        15,        85],
       [202212396,        95,        30,

(방법2)

In [40]:
pd.DataFrame(test_dic).T

att  rep  mid  fin
202212380   65   55   50   40
202212370   95  100   50   80
202212363   65   90   60   30
202212488   55   80   75   80
202212312   80   30   30  100
202212377   75   40  100   15
202212463   65   45   45   90
202212471   60   60   25    0
202212400   95   65   20   10
202212469   90   80   80   20
202212318   55   75   35   25
202212432   95   95   45    0
202212443   95   55   15   35
202212367   50   80   40   30
202212458   50   55   15   85
202212396   95   30   30   95
202212482   50   50   45   10
202212452   65   55   15   45
202212387   70   70   40   35
202212354   90   90   80   90

(방법3)

In [41]:
test_dic2 = {'att':{key[i]:att[i] for i in range(20)},
             'rep':{key[i]:rep[i] for i in range(20)},
             'mid':{key[i]:mid[i] for i in range(20)},
             'fin':{key[i]:fin[i] for i in range(20)}}

In [44]:
pd.DataFrame(test_dic2)

att  rep  mid  fin
202212380   65   55   50   40
202212370   95  100   50   80
202212363   65   90   60   30
202212488   55   80   75   80
202212312   80   30   30  100
202212377   75   40  100   15
202212463   65   45   45   90
202212471   60   60   25    0
202212400   95   65   20   10
202212469   90   80   80   20
202212318   55   75   35   25
202212432   95   95   45    0
202212443   95   55   15   35
202212367   50   80   40   30
202212458   50   55   15   85
202212396   95   30   30   95
202212482   50   50   45   10
202212452   65   55   15   45
202212387   70   70   40   35
202212354   90   90   80   90

(방법4)

In [48]:
df = pd.DataFrame({'att':att, 'rep':rep, 'mid':mid, 'fin':fin}, index=key)
df

att  rep  mid  fin
202212380   65   55   50   40
202212370   95  100   50   80
202212363   65   90   60   30
202212488   55   80   75   80
202212312   80   30   30  100
202212377   75   40  100   15
202212463   65   45   45   90
202212471   60   60   25    0
202212400   95   65   20   10
202212469   90   80   80   20
202212318   55   75   35   25
202212432   95   95   45    0
202212443   95   55   15   35
202212367   50   80   40   30
202212458   50   55   15   85
202212396   95   30   30   95
202212482   50   50   45   10
202212452   65   55   15   45
202212387   70   70   40   35
202212354   90   90   80   90

(방법5)

In [49]:
df = pd.DataFrame({'att':att, 'rep':rep, 'mid':mid, 'fin':fin})
df

att  rep  mid  fin
0    65   55   50   40
1    95  100   50   80
2    65   90   60   30
3    55   80   75   80
4    80   30   30  100
5    75   40  100   15
6    65   45   45   90
7    60   60   25    0
8    95   65   20   10
9    90   80   80   20
10   55   75   35   25
11   95   95   45    0
12   95   55   15   35
13   50   80   40   30
14   50   55   15   85
15   95   30   30   95
16   50   50   45   10
17   65   55   15   45
18   70   70   40   35
19   90   90   80   90

In [50]:
df = df.set_index([key])
df

att  rep  mid  fin
202212380   65   55   50   40
202212370   95  100   50   80
202212363   65   90   60   30
202212488   55   80   75   80
202212312   80   30   30  100
202212377   75   40  100   15
202212463   65   45   45   90
202212471   60   60   25    0
202212400   95   65   20   10
202212469   90   80   80   20
202212318   55   75   35   25
202212432   95   95   45    0
202212443   95   55   15   35
202212367   50   80   40   30
202212458   50   55   15   85
202212396   95   30   30   95
202212482   50   50   45   10
202212452   65   55   15   45
202212387   70   70   40   35
202212354   90   90   80   90

### 해싱으로 원하는 정보를 뽑으면 좋겠다. (마치 딕셔너리처럼)

`-` 예제1: 출석점수를 출력

In [51]:
test_dic2['att']

{'202212380': 65,
 '202212370': 95,
 '202212363': 65,
 '202212488': 55,
 '202212312': 80,
 '202212377': 75,
 '202212463': 65,
 '202212471': 60,
 '202212400': 95,
 '202212469': 90,
 '202212318': 55,
 '202212432': 95,
 '202212443': 95,
 '202212367': 50,
 '202212458': 50,
 '202212396': 95,
 '202212482': 50,
 '202212452': 65,
 '202212387': 70,
 '202212354': 90}

In [52]:
df['att']

202212380    65
202212370    95
202212363    65
202212488    55
202212312    80
202212377    75
202212463    65
202212471    60
202212400    95
202212469    90
202212318    55
202212432    95
202212443    95
202212367    50
202212458    50
202212396    95
202212482    50
202212452    65
202212387    70
202212354    90
Name: att, dtype: int64

`-` 예제2: 학번 202212380의 출석점수 출력

In [54]:
test_dic2['att']['202212380']

65

In [55]:
df['att']['202212380']

65

### 인덱싱으로 정보를 뽑는 기능도 지원하면 좋겠다. (마치 리스트나 넘파이처럼)

`-` 예제1: 첫번째 학생의 기말고사 성적을 출력하고 싶다.

In [56]:
test_ndarray[0,-1]

40

In [57]:
df.iloc[0,-1]

40

- 벼락치기: df에서 iloc이라는 특수기능을 이용하면 넘파이 인덱싱처럼 원소출력이 가능하다.

`-` 예제2: 홀수번째 학생의 점수를 뽑고 싶다.

In [58]:
test_ndarray[::2]

array([[202212380,        65,        55,        50,        40],
       [202212363,        65,        90,        60,        30],
       [202212312,        80,        30,        30,       100],
       [202212463,        65,        45,        45,        90],
       [202212400,        95,        65,        20,        10],
       [202212318,        55,        75,        35,        25],
       [202212443,        95,        55,        15,        35],
       [202212458,        50,        55,        15,        85],
       [202212482,        50,        50,        45,        10],
       [202212387,        70,        70,        40,        35]])

In [59]:
df.iloc[::2]

att  rep  mid  fin
202212380   65   55   50   40
202212363   65   90   60   30
202212312   80   30   30  100
202212463   65   45   45   90
202212400   95   65   20   10
202212318   55   75   35   25
202212443   95   55   15   35
202212458   50   55   15   85
202212482   50   50   45   10
202212387   70   70   40   35

`-` 예제3: 맨 끝에서 3명의 점수를 출력하고 싶다.

In [60]:
test_ndarray[-3:]

array([[202212452,        65,        55,        15,        45],
       [202212387,        70,        70,        40,        35],
       [202212354,        90,        90,        80,        90]])

In [62]:
df.iloc[-3:]

att  rep  mid  fin
202212452   65   55   15   45
202212387   70   70   40   35
202212354   90   90   80   90

`-` 예제4: 맨 끝에서 3명의 점수 중 마지막 2개의 칼럼만 출력하고 싶다.

In [63]:
test_ndarray[-3:,-2:]

array([[15, 45],
       [40, 35],
       [80, 90]])

In [64]:
df.iloc[-3:,-2:]

mid  fin
202212452   15   45
202212387   40   35
202212354   80   90

### 궁극: 해싱과 인덱싱을 모두 지원하는 아주 우수한 자료형을 만들고 싶음.

`-` 예제1: 중간고사 점수가 20점 이상이면서 동시에 출석점수가 60점미만인 학생들의 기말고사 점수를 출력

In [65]:
df.query('mid >= 20 and att < 60')

att  rep  mid  fin
202212488   55   80   75   80
202212318   55   75   35   25
202212367   50   80   40   30
202212482   50   50   45   10

In [66]:
df.query('mid >= 20 and att < 60')['fin']

202212488    80
202212318    25
202212367    30
202212482    10
Name: fin, dtype: int64

(방법2) 넘파이 스타일이라면?

In [67]:
test_ndarray

array([[202212380,        65,        55,        50,        40],
       [202212370,        95,       100,        50,        80],
       [202212363,        65,        90,        60,        30],
       [202212488,        55,        80,        75,        80],
       [202212312,        80,        30,        30,       100],
       [202212377,        75,        40,       100,        15],
       [202212463,        65,        45,        45,        90],
       [202212471,        60,        60,        25,         0],
       [202212400,        95,        65,        20,        10],
       [202212469,        90,        80,        80,        20],
       [202212318,        55,        75,        35,        25],
       [202212432,        95,        95,        45,         0],
       [202212443,        95,        55,        15,        35],
       [202212367,        50,        80,        40,        30],
       [202212458,        50,        55,        15,        85],
       [202212396,        95,        30,

In [70]:
test_ndarray[:,3] >= 20 ## 중간고사가 20점이상

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True, False,
        True,  True])

In [75]:
test_ndarray[:,1] < 60 ## 출석이 60미만 

array([False, False, False,  True, False, False, False, False, False,
       False,  True, False, False,  True,  True, False,  True, False,
       False, False])

In [76]:
(test_ndarray[:,3] >= 20) & (test_ndarray[:,1] < 60)

array([False, False, False,  True, False, False, False, False, False,
       False,  True, False, False,  True, False, False,  True, False,
       False, False])

> note: test_ndarray[:,3] >= 20 & test_ndarray[:,1] >= 60와 같이 하면 에러가 난다. 조심하자! **괄호!!!**

In [78]:
test_ndarray[(test_ndarray[:,3] >= 20) & (test_ndarray[:,1] < 60),-1]

array([80, 25, 30, 10])

- 구현난이도 어려움, 가독성 꽝..

`-` 예제2: `중간고사점수<기말고사점수`인 학생들의 출석점수 평균을 구하자.

In [82]:
df.query('mid < fin')

att  rep  mid  fin
202212370   95  100   50   80
202212488   55   80   75   80
202212312   80   30   30  100
202212463   65   45   45   90
202212443   95   55   15   35
202212458   50   55   15   85
202212396   95   30   30   95
202212452   65   55   15   45
202212354   90   90   80   90

In [81]:
df.query('mid < fin')['att'].mean()

76.66666666666667

### pandas 공부 1단계

#### 데이터프레임 선언

`-` 방법1: dictionary에서 만든다.

In [ ]:
pd.DataFrame({'att':[30,40,50], 'mid':[50,60,70]}