## 데이터의 유형

선형대수에서 다루는 데이터는 개수나 형태에 따라 크게 **스칼라(scalar), 벡터(vector), 행렬(matrix), 텐서(tensor)** 유형으로 나뉜다. 스칼라는 숫자 하나로 이루어진 데이터이고, 벡터는 여러 숫자로 이루어진 데이터 레코드(data record)이며, 행렬은 이러한 벡터, 즉 데이터 레코드가 여럿인 데이터 집합이라고 볼 수 있다. 텐서는 같은 크기의 행렬이 여러 개 있는 것이라고 생각하면 된다.

In [3]:
import numpy as np

In [9]:
# 열 벡터
x1 = np.array([[5.1], [3.5], [1.4], [0.2]])
print(x1)
print(x1.shape)

[[5.1]
 [3.5]
 [1.4]
 [0.2]]
(4, 1)


In [8]:
# 행 벡터
x2 = np.array([5.1, 3.5, 1.4, 0.2])
print(x2)
print(x2.shape)

[5.1 3.5 1.4 0.2]
(4,)


In [12]:
# 행렬
A = np.array([[11,12,13],[14,15,16]])
A

array([[11, 12, 13],
       [14, 15, 16]])

In [13]:
A.shape

(2, 3)

In [15]:
# 전치행렬
print(A.T)

[[11 14]
 [12 15]
 [13 16]]


In [16]:
# 벡터의 전치는?
print("x1=")
print(x1.T)
print(x1.T.shape)

x1=
[[5.1 3.5 1.4 0.2]]
(1, 4)


## 행렬의 역행렬

In [28]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])

In [29]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

## 행렬의 활용 (연립방정식 풀이)

$\begin{cases} 2x + 3y = 1 \\ x-2y = 4 \end{cases}$

In [17]:
A = np.array([[2,3], [1,-2]])
b = np.array([[1], [4]])

In [22]:
A.shape, b.shape

((2, 2), (2, 1))

In [23]:
print(A)

[[ 2  3]
 [ 1 -2]]


In [25]:
print(b)

[[1]
 [4]]


In [27]:
x = np.linalg.inv(A) @ b
x

array([[ 2.],
       [-1.]])

FHD: 3 x 1080 x 1920